/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi;

/**
 *
 * @author dandi
 */

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class data_barang extends javax.swing.JFrame {

    String user = "root";
    String pwd = "";
    String host = "localhost";
    String db = "db_barang";
    String url = "";
    
    public data_barang() {
        initComponents();
        load_table();
        clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edit = new javax.swing.JButton();
        nama_b = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        jenis_b = new javax.swing.JLabel();
        id_b = new javax.swing.JLabel();
        stok_b = new javax.swing.JLabel();
        id_barang = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jenis_brg = new javax.swing.JTextField();
        stok = new javax.swing.JTextField();
        data_pelanggan = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_pelanggan = new javax.swing.JTable();
        reset = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        master = new javax.swing.JMenu();
        pelanggan = new javax.swing.JMenuItem();
        barang = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        transaksi_brg = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();
        laporan_trs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        nama_b.setText("Nama Barang");

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jenis_b.setText("Jenis Barang");

        id_b.setText("ID Bsrang");

        stok_b.setText("Stok");

        id_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_barangActionPerformed(evt);
            }
        });

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        data_pelanggan.setText("DATA BARANG");

        save.setText("Simpan");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        tabel_pelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pelangganMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabel_pelanggan);

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        master.setText("Master");

        pelanggan.setText("Pelanggan");
        pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganActionPerformed(evt);
            }
        });
        master.add(pelanggan);

        barang.setText("Barang");
        barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangActionPerformed(evt);
            }
        });
        master.add(barang);

        menu.add(master);

        transaksi.setText("Transkasi");

        transaksi_brg.setText("Transaksi Barang");
        transaksi_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksi_brgActionPerformed(evt);
            }
        });
        transaksi.add(transaksi_brg);

        menu.add(transaksi);

        laporan.setText("Laporan");

        laporan_trs.setText("Transaksi Barang");
        laporan_trs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_trsActionPerformed(evt);
            }
        });
        laporan.add(laporan_trs);

        menu.add(laporan);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jenis_b)
                                    .addComponent(stok_b)
                                    .addComponent(id_b))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jenis_brg, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                            .addComponent(stok)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                        .addComponent(id_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nama_b)
                                .addGap(44, 44, 44)
                                .addComponent(nama))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(data_pelanggan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(data_pelanggan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_b, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama_b, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenis_b)
                    .addComponent(jenis_brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stok_b)
                    .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(edit)
                    .addComponent(delete)
                    .addComponent(reset))
                .addGap(68, 68, 68)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganActionPerformed
        // TODO add your handling code here:
        new data_pelanggan().show();
        this.dispose();
    }//GEN-LAST:event_pelangganActionPerformed

    private void barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangActionPerformed
        // TODO add your handling code here:
        new data_barang().show();
        this.dispose();
    }//GEN-LAST:event_barangActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="UPDATE barang SET nama_barang = '"+nama.getText()+"', jenis_barang = '"+jenis_brg.getText()+"',stok= '"+stok.getText()+"' WHERE id_barang = '"+id_barang.getText()+"'";
            java.sql.Connection conn = (Connection)Db_Connection.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Edir");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
        load_table();
        clear();
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="DELETE FROM barang WHERE id_barang='"+id_barang.getText()+"'";
            java.sql.Connection conn=(Connection)Db_Connection.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Berhasil Di Hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
        clear();
    }//GEN-LAST:event_deleteActionPerformed

    private void id_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_barangActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:

        try{
            Class.forName("com.mysql.jdbc.Driver");
            url = "jdbc:mysql://"+host+"/"+db;
            String sql = "INSERT INTO barang"+"(id_barang, nama_barang, jenis_barang, stok)"+"VALUES(?,?,?,?)";
            Connection con = (Connection)Db_Connection.configDB();
            PreparedStatement st = null;

            st = con.prepareStatement(sql);
            st.setString(1, id_barang.getText());
            st.setString(2, nama.getText());
            st.setString(3, jenis_brg.getText());
            st.setString(4, stok.getText());
            st.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
        clear();
    }//GEN-LAST:event_saveActionPerformed

    private void tabel_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pelangganMouseClicked
        // TODO add your handling code here:
        int baris = tabel_pelanggan.rowAtPoint(evt.getPoint());
        String inputid = tabel_pelanggan.getValueAt(baris, 1).toString();
        id_barang.setText(inputid);
        String inputnama = tabel_pelanggan.getValueAt(baris, 2).toString();
        nama.setText(inputnama);
        String inputjenis = tabel_pelanggan.getValueAt(baris, 3).toString();
        jenis_brg.setText(inputjenis);
        String inputstok= tabel_pelanggan.getValueAt(baris, 4).toString();
        stok.setText(inputstok);
    }//GEN-LAST:event_tabel_pelangganMouseClicked

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_resetActionPerformed

    private void transaksi_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksi_brgActionPerformed
        // TODO add your handling code here:
        new transaksi_barang().show();
        this.dispose(); 
    }//GEN-LAST:event_transaksi_brgActionPerformed

    private void laporan_trsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_trsActionPerformed
        // TODO add your handling code here:
        new laporan().show();
        this.dispose();
    }//GEN-LAST:event_laporan_trsActionPerformed

    private void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("ID Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Jenis Barang");
        model.addColumn("Stok Barang");
        
        try {
            int no = 1;
            String sql = "SELECT * FROM barang";
            Connection con = (Connection)Db_Connection.configDB();
            Statement stm = con.createStatement();
            ResultSet res = stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{
                    no++,
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4)});
            }
            tabel_pelanggan.setModel(model);
        } catch (Exception e) {
            }
    }
    
    private void clear(){
        id_barang.setText(null);
        nama.setText(null);
        jenis_brg.setText(null);
        stok.setText(null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem barang;
    private javax.swing.JLabel data_pelanggan;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JLabel id_b;
    private javax.swing.JTextField id_barang;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jenis_b;
    private javax.swing.JTextField jenis_brg;
    private javax.swing.JMenu laporan;
    private javax.swing.JMenuItem laporan_trs;
    private javax.swing.JMenu master;
    private javax.swing.JMenuBar menu;
    private javax.swing.JTextField nama;
    private javax.swing.JLabel nama_b;
    private javax.swing.JMenuItem pelanggan;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    private javax.swing.JTextField stok;
    private javax.swing.JLabel stok_b;
    private javax.swing.JTable tabel_pelanggan;
    private javax.swing.JMenu transaksi;
    private javax.swing.JMenuItem transaksi_brg;
    // End of variables declaration//GEN-END:variables
}
