/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi;

/**
 *
 * @author dandi
 */

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class laporan extends javax.swing.JFrame {
    
    String user = "root";
    String pwd = "";
    String host = "localhost";
    String db = "db_barang";
    String url = "";
    private DefaultTableModel model;

    public laporan() {
        initComponents();
        
        model = new DefaultTableModel();
        tabel_laporan.setModel(model);
        model.addColumn("No");
        model.addColumn("Jenis Transaksi");
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Jenis Barang");
        model.addColumn("Tanggal");
        model.addColumn("Banyak Barang");
        model.addColumn("Total");        
        getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_laporan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        master = new javax.swing.JMenu();
        pelanggan = new javax.swing.JMenuItem();
        barang = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        transaksi_brg = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();
        laporan_trs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabel_laporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_laporan);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("LAPORAN TRANSAKSI");

        master.setText("Master");

        pelanggan.setText("Pelanggan");
        pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganActionPerformed(evt);
            }
        });
        master.add(pelanggan);

        barang.setText("Barang");
        barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangActionPerformed(evt);
            }
        });
        master.add(barang);

        menu.add(master);

        transaksi.setText("Transkasi");

        transaksi_brg.setText("Transaksi Barang");
        transaksi_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksi_brgActionPerformed(evt);
            }
        });
        transaksi.add(transaksi_brg);

        menu.add(transaksi);

        laporan.setText("Laporan");

        laporan_trs.setText("Transaksi Barang");
        laporan_trs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_trsActionPerformed(evt);
            }
        });
        laporan.add(laporan_trs);

        menu.add(laporan);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganActionPerformed
        // TODO add your handling code here:
        new data_pelanggan().show();
        this.dispose();
    }//GEN-LAST:event_pelangganActionPerformed

    private void barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangActionPerformed
        // TODO add your handling code here:
        new data_barang().show();
        this.dispose();
    }//GEN-LAST:event_barangActionPerformed

    private void transaksi_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksi_brgActionPerformed
        // TODO add your handling code here:
        new transaksi_barang().show();
        this.dispose(); 
    }//GEN-LAST:event_transaksi_brgActionPerformed

    private void laporan_trsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_trsActionPerformed
        // TODO add your handling code here:
        new laporan().show();
        this.dispose();
    }//GEN-LAST:event_laporan_trsActionPerformed

    private void getData(){
 
        try {
            String sql = "SELECT * FROM laporan";
            Connection con = (Connection)Db_Connection.configDB();
            Statement stm = con.createStatement();
            ResultSet res = stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6),
                    res.getString(7),
                    res.getString(8)});
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem barang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu laporan;
    private javax.swing.JMenuItem laporan_trs;
    private javax.swing.JMenu master;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem pelanggan;
    private javax.swing.JTable tabel_laporan;
    private javax.swing.JMenu transaksi;
    private javax.swing.JMenuItem transaksi_brg;
    // End of variables declaration//GEN-END:variables
}
